### ISSUE TITLE
Not getting expected CCI values

### ISSUE THREAD

**Issue by MehdiAnis** [lppkarl/Trady#103]
I used 200 made up data points to test CCI. My Data 
High  Low  Close
  1        1       1
  2        1       1
  3        1       1
  4        1       1
---     ---     ---
 200     1       1

in my excel calculation CCI values comes for each row = 66.66666667
Using candles.Cci(Period); gives me CCI = 123.80952380952380952380952381

I am attaching my excel file that I used for CCI calculation. Not sure why I am getting different result than the Trady CCI, any help appreciated. Thanks.

[Trady_CCI_Check.xlsx](https://github.com/lppkarl/Trady/files/4027893/Trady_CCI_Check.xlsx)

**Comment by lppkarl** [comment]
@MehdiAnis the fix is deployed to nuget, please update the package accordingly

**Comment by MehdiAnis** [comment]
I think I interpreted the CCI Calculation Formula differently, thus my numbers are different,

**Comment by lppkarl** [comment]
@MehdiAnis Yes, I find that our interpretation are different. My version is getting the deviation using Abs(n-th TP - 14-th TP SMA) while yours is Abs(n-th TP - n-th TP SMA), I believe your version is a more accurate one, so I changed it. Most of the time, I find that there're some variations of formula for technical indicators, and I have to cross check the logic with different formula provide e.g. Wiki, Stockcharts, investopedia, etc. Anyway, I will end this issue. Thanks for your support on this library :)
