### ISSUE TITLE
Additional indicators

### ISSUE THREAD

**Issue by sthewissen** [lppkarl/Trady#11]
I don't know what kind of indicators are still on the to do list, but I'd love to see the following:

- Parabolic SAR / SAR
- Momentum Index
- CCI

Great library!

**Comment by lppkarl** [comment]
@sthewissen Thanks for the praise! The indicators are marked in backlog 😄

**Comment by lppkarl** [comment]
@sthewissen I have just released a beta version on this issue, just let you know 😄
