### ISSUE TITLE
Need Help With Custom Importer

### ISSUE THREAD

**Issue by OryCore** [lppkarl/Trady#120]
Hi, First of all, it is an incredible library. I really appreciate the work that has done.
I am using [Binance.Net](https://github.com/JKorf/Binance.Net) API To get data from Binance 
but I couldn't create a custom Importer to use the indicator functions of the Trady library. 
This is what I have done so far: 
![Screenshot_2](https://user-images.githubusercontent.com/63416552/107632509-a3350100-6c77-11eb-8994-31bdf0049bca.png)
I need your help to fix the code and to use those data with Trady indicator features.
Thank you in advance for your help.

**Comment by ridicoulous** [comment]
you have to use [Binance spot api client](https://github.com/JKorf/Binance.Net/blob/a418bf640b82a279588f14bb60b8c8bd2ee0e484/Binance.Net/SubClients/Spot/BinanceClientSpotMarket.cs#L207) instead socket. 
`ImportAsync` method implies to get data by request, without subscribing to data producer and waiting pushes from server side

**Comment by OryCore** [comment]
thank you for your answer. I have fixed that part but I still don't know how am I going to return these data? I mean the last line
![](https://user-images.githubusercontent.com/63416552/107632509-a3350100-6c77-11eb-8994-31bdf0049bca.png)

**Comment by ridicoulous** [comment]
I didn't understand you. Show me your new code with fixes

**Comment by OryCore** [comment]
There are not too many changes done to the code that would affect this part. If you look at the line that starts with "await client"
you can see that I am already using the "Spot" subclient. I have no issues getting the data from Binance. I need to take the data indicated as (Time, Open, High, Close, Volume) in the subscribeTotickerUpdatesAsync part, and somehow put those data to the corresponding parts at the last line. But I don't know how to do it and every trial that I had given me errors.
This is what I mean.
![InkedScreenshot_1_LI](https://user-images.githubusercontent.com/63416552/107643382-1bef8980-6c87-11eb-8354-17300f82b86f.jpg)

**Comment by ridicoulous** [comment]
> you have to use [Binance spot api client](https://github.com/JKorf/Binance.Net/blob/a418bf640b82a279588f14bb60b8c8bd2ee0e484/Binance.Net/SubClients/Spot/BinanceClientSpotMarket.cs#L207) instead socket.
> `ImportAsync` method implies to get data by request, without subscribing to data producer and waiting pushes from server side

Read this answer again and compare it with your code. You use **Socket** client insead **API** client. If follow my link, you can see that I advised to use `GetKlinesAsync` method of api client

>  I have no issues getting the data from Binance

You have the issue with binance clients purposes. One of them (API client) takes data on demand, second - (Socket client) subscribes to data streams and pushes each update into the event stream

**Comment by OryCore** [comment]
Ohh sorry. Now I see what you are trying to tell. I changed my code to this:
![Screenshot_2](https://user-images.githubusercontent.com/63416552/107648155-05e4c780-6c8d-11eb-8f66-2ecd258ed801.png)
But now The return line gives this error
![wwwwwwwwwwwwwwwwwwwwwww](https://user-images.githubusercontent.com/63416552/107648218-139a4d00-6c8d-11eb-8d2a-b055d7b55c7f.png)
And thank you for Helping. I have been struggling with this for almost a week now.

**Comment by OryCore** [comment]
Do you know how to get rid of this error?

![](https://user-images.githubusercontent.com/63416552/107648218-139a4d00-6c8d-11eb-8d2a-b055d7b55c7f.png)

**Comment by ridicoulous** [comment]
cause `WebCallResult<T>` does not emplements `IEnumerable` interface. Look to the `Data` field of result of request. 
I advise you to learn in more detail what you are working with

**Comment by OryCore** [comment]
Well if I can't get it as IEnumerable how am I going to return the data

> I advise you to learn in more detail what you are working with

Yeah, that would Be Useful but Unfortunately, I don't have time right now.

**Comment by ridicoulous** [comment]
> Well if I can't get it as IEnumerable how am I going to return the data

You shouldn't get `WebCallResult` as `IEnumerable`.  You have to look inside this class and get collection from it (`result.Data`). Also you have to find time to deep into details of programming at whole and your instruments if you want to achieve some profit

**Comment by OryCore** [comment]
Thank you for your advice and help I think I got everything Here is the final code:
![Screenshot_1](https://user-images.githubusercontent.com/63416552/107681329-f7f46e00-6caf-11eb-8ac5-1520d7f6bf52.png)
Thank you so much again. I have been struggling with these 2 lines of code for a week now.
