### ISSUE TITLE
PeriodOption of Per5Minute and Per10Minute 

### ISSUE THREAD

**Issue by mkinawy** [lppkarl/Trady#22]
Thanks for the great stuff.

Today I faced this problem, I built a custom importer for an exchange that supports 5-min and 10-min candles, but I didn't find those in the passed `PeriodOption` enum. I think those are important to be added as I see lots of exchanges out there supporting those periods, and those periods are very important for day traders.

**Comment by lppkarl** [comment]
@mkinawy Thanks for pointing out this, the periodOption will be added in the next iteration 😄

**Comment by mkinawy** [comment]
@lppkarl thanks!
