### ISSUE TITLE
Fully understand the Strategy building & backtesting sample

### ISSUE THREAD

**Issue by objecta** [lppkarl/Trady#26]
Hi
I'm investigating and testing possible tools to help me build a simple analyse tool to be user with Bittrex.
I found You Trady and You implementation of BackTest, Builder and rules.

In the Strategy building & backtesting sample You mention 

// Create portfolio instance by using PortfolioBuilder
var runner = new Builder()
    .Add(equity, 10)
    .Add(equity2, 30)
    .Buy(buyRule)
    .Sell(sellRule)
    .Build();

For me to fully understand this I would kindly ask if You could include some more code that show how the  equity and equity2 is created.

I'm new into Technical indicators, trading  and cryptcoins and is trying to learn more about these subjects.

I managed to add a working Bittrex import, so I can start testing some of me ideas

Best regards
Klaus E. Frederiksen
Denmark

**Comment by lppkarl** [comment]
@objecta Sorry for the late response, missing code has been added to README. To be precise, the equity object is the candle list, it is imported from importer or created manually. For instance, the code would look like:
```
var importer = new YahooFinanceImporter();
var equity = await importer.ImportAsync("FB");
var equity2 = await importer.ImportAsync("AAPL");
```

**Comment by lppkarl** [comment]
Closed of being inactive for a long time.
