### ISSUE TITLE
CLR Exception - Stochastics.Fast

### ISSUE THREAD

**Issue by JohnieBraaf** [lppkarl/Trady#27]
Hi, I'm running into issues computing the stachastics Fast indicator.

The code that I used:
var stoch3 = new Stochastics.Fast(candles, 3, 3).Compute();

The error that I get:
Managed Debugging Assistant 'FatalExecutionEngineError' 
  Message=Managed Debugging Assistant 'FatalExecutionEngineError' : 'The runtime has encountered a fatal error. The address of the error was at 0x2dfa7486, on thread 0xc710. The error code is 0xc0000005. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.'

Am I using an incorrect method of computing the indicator here or is there an actual issue?

**Comment by Ricky-G** [comment]
What is the underlying dataset you are using, it possible to paste a few data rows of the csv

**Comment by JohnieBraaf** [comment]
Hi Ricky,

Thanks for your reply, I've made a short example that reproduces the issues:

`var candles = new List<Candle>();
 for (int i=0; i<50; i++)
 {
     candles.Add(new Candle(DateTime.Now.AddDays(i), i, i, i, i, i));
 }
               
 var rsi14 = new RelativeStrengthIndex(candles, 14).Compute(); // works
 var stoch3 = new Stochastics.Fast(candles, 3, 1).Compute();   // crashes`

The error seems to be, due to the fact that start and end index of the array stay NULL.

![image](https://user-images.githubusercontent.com/1111346/34013323-469df8aa-e117-11e7-931d-6083ae593bbf.png)

**Comment by lppkarl** [comment]
@JohnieBraaf Sorry for the late response. I've tried your code with my mac running .NET Core 2.0 and the code works perfectly. 

This library is a fully-managed library & do not contains any unsafe code. I'm suspecting it's happened only in older version of .NET, may I know the .NET version & the platform you're using?

**Comment by JohnieBraaf** [comment]
Hi lpparl,

I've tried multiple versions among which 4.5 and 4.62. In Visual Studio 2017. (attached sample project)

When I analyze it in detail, it seems somehow related to the fact that it is unable to handle the multiple return values of the Stochastic.Fast ComputeByIndexImpl.

As if it is trying to return 1 and other times 3 tuple values in the same array.

Is there any alternative method that I can use?

**Comment by lppkarl** [comment]
Hmm.. Do you mean you are unable to get the return values if the indicator returns a tuple list? 

I mean the indicator itself is designed to return tuple list, there's also other indicators which returns tuple list. If I have changed it to return single values, it requires some work but I think it's not the best way to do this as it seems it's rather a bug that is not related to this library :confused:

**Comment by JohnieBraaf** [comment]
Hi lppkarl, I've tried some different indicators that are not returning a tuple and I'm getting the same error presented. 

I think you are right that it seems to be some sort of Microsoft bug, At this point I'm giving it up..., for now. Thnx in any case

**Comment by lppkarl** [comment]
Sorry to hear that. I will try to dig deep to the fatalexecutionengineerror to see what's going wrong with the call. But at the time being, would you mind I close the issue as it's a bug that is out of the scope of this library?

**Comment by JohnieBraaf** [comment]
Closed, thank you
