### ISSUE TITLE
Streamable Candles

### ISSUE THREAD

**Issue by byteshadow** [lppkarl/Trady#29]
I've made a change to AnalyzableBase to allow for Candles to be streamed, rather than having to pass in the entire collection every time. ~~if you can kindly create a branch where I can push these changes for you to review~~. I have a fork where progress can be reviewed. :) [ObservableAnalyzableBase](https://github.com/byteshadow/Trady/tree/feature/observableAnalyzableBase)
thanks,
Mina

**Comment by lppkarl** [comment]
@byteshadow Thanks for your effort 😄 I'm looking forward to it 👍

**Comment by lppkarl** [comment]
Merge to #59 for more exposure
