### ISSUE TITLE
Nonlinear time to compute sma

### ISSUE THREAD

**Issue by kelthar** [lppkarl/Trady#30]
I'm using this code to test the performance of Sma. I'm wondering why I don't get a linear time increase when I raise the number of items to calculate. Will this be the same with all indicators? Is it possible to mitigate this in some way?

            DateTime then = DateTime.Now;
            var t = candles.Sma(30, 0, 100);
            System.Diagnostics.Debug.WriteLine(DateTime.Now.Subtract(then).TotalMilliseconds);

            then = DateTime.Now;
            t = candles.Sma(30, 0, 1000);
            System.Diagnostics.Debug.WriteLine(DateTime.Now.Subtract(then).TotalMilliseconds);

            then = DateTime.Now;
            t = candles.Sma(30, 0, 10000);
            System.Diagnostics.Debug.WriteLine(DateTime.Now.Subtract(then).TotalMilliseconds);

            then = DateTime.Now;
            t = candles.Sma(30, 0, 100000);
            System.Diagnostics.Debug.WriteLine(DateTime.Now.Subtract(then).TotalMilliseconds);

The output is:
80,0151
38,0028
576,0439
52473,7246

I'm using version 3.0.0

**Comment by kelthar** [comment]
When using GetRange instead of Skip/Take 100000 candles takes 502ms instead of 52473ms.

It's this line:
mappedInputs.Skip(index - PeriodCount + 1).Take(PeriodCount).Average() : null;

Changed to this:
(mappedInputs as List<decimal?>).GetRange(index - PeriodCount + 1, PeriodCount).Average() : null;

**Comment by byteshadow** [comment]
nice one @kelthar  would be able to push that change?

**Comment by kelthar** [comment]
It's actually a hack, I would say. More to illustrate a possible speedup. I think there would need to be a bigger rewrite to implement this. I moved away to another lib when I saw how bad the performance is in rule evaluation, etc. There's a lot of good abstractions here, but this lib is not built with performance in mind :\.

**Comment by byteshadow** [comment]
I am working on increasing the performance of this library, i also do like the abstraction in here and after a while its very easy to understand what is going on, and the unit tests are top class. Do you mind sharing the new library you are using?
also if you want to see the changes I'm making you can follow it here  [ObservableAnalyzableBase](https://github.com/byteshadow/Trady/tree/feature/observableAnalyzableBase)

**Comment by lppkarl** [comment]
@kelthar You're right, this lib is built for ease of use, and it's designed to be extensive & modular such that anyone could easily modify it to how they want, but I agree there is a lack of performance in a trade of configurability, and I haven't really optimize it yet. 

In addition to your comment, I wonder if you could tell me how bad the performance in rule evaluation is. I'm not being offensive on that, but I want to know which part of it is killing the performance so I could make improvement on it.

Again, thanks for your precious comment on this lib 👍
