### ISSUE TITLE
Improve for CSV importer

### ISSUE THREAD

**Issue by lexruster** [lppkarl/Trady#33]
Hi, @lppkarl 

I have a suggestion (actually if I contribute, are you open to review pull requests :) ?)
Csc import now is 
``` C#
 return new Candle(
                csv.GetField<DateTime>(0),
                csv.GetField<Decimal>(1),
                csv.GetField<Decimal>(2),
                csv.GetField<Decimal>(3),
                csv.GetField<Decimal>(4),
                csv.GetField<Decimal>(5)
            );
```

But CsvHelper supports auto parsing by field names. I suggest doing that 
var myDatas = csvReader.GetRecords<Candle>().ToList();

For example, i spent half an hour before look at code to find out that header is ignored

**Comment by lppkarl** [comment]
@lexruster PR is always welcomed :)

**Comment by irperez** [comment]
@lexruster I just noticed this.  I put in a PR a few months ago where you can put in options to configure the CsvImporter.  

Check out the new class here:
[https://github.com/lppkarl/Trady/blob/f937855d19517480c283dab0887701a421847857/Trady.Importer.Csv/CsvImportConfiguration.cs#L6-L15](https://github.com/lppkarl/Trady/blob/f937855d19517480c283dab0887701a421847857/Trady.Importer.Csv/CsvImportConfiguration.cs#L6-L15)

You would then use this constructor:
[https://github.com/lppkarl/Trady/blob/f937855d19517480c283dab0887701a421847857/Trady.Importer.Csv/CsvImporter.cs#L36](https://github.com/lppkarl/Trady/blob/f937855d19517480c283dab0887701a421847857/Trady.Importer.Csv/CsvImporter.cs#L36)

Example Usage here:
[https://github.com/lppkarl/Trady/blob/f937855d19517480c283dab0887701a421847857/Trady.Test/ImporterTest.cs#L84-L99](https://github.com/lppkarl/Trady/blob/f937855d19517480c283dab0887701a421847857/Trady.Test/ImporterTest.cs#L84-L99)

This is only available via the 3.1 release which may not be available in the NuGet package just yet.  I've asked @lppkarl to push the latest to NuGet.  But I haven't seen it go up yet.
[https://github.com/lppkarl/Trady/issues/28](https://github.com/lppkarl/Trady/issues/28)

**Comment by lexruster** [comment]
Thank you @irperez , yes I saw it already in PR)
But it still not about custom headers. I just should implement it and post PR, may be, someday)

**Comment by lppkarl** [comment]
The issue is no longer active, close.
