### ISSUE TITLE
Update CsvHelper

### ISSUE THREAD

**Issue by lexruster** [lppkarl/Trady#36]
Used in project CsvHelper 2.16.3 and latest 6.1.1 not compatible.
If you use custom Importer with CsvHelper 6 app is break, because CsvHelper has breaked changes.

```
Could not load type 'CsvHelper.Configuration.CsvConfiguration' from assembly 'CsvHelper, Version=6.0.0.0, Culture=neutral, PublicKeyToken=8c4959082be5c823'.
```
And CsvHelper.Configuration.CsvConfiguration really not exists in 6

**Comment by lppkarl** [comment]
The latest version should include CsvHelper (>6.0.0), the issue is probably solved, close.
