### ISSUE TITLE
Could not figure out how to use candlesticks with backtest

### ISSUE THREAD

**Issue by alikalfaoglu** [lppkarl/Trady#38]
Can you provide a sample for that? 

For ex; suppose I have a set of candles and I want to determine whether it's a bullish or bearish engulfing pattern using backtest.

I couldn't find any extension that will help me using in buy/sell rules.

**Comment by alikalfaoglu** [comment]
I figured it out all. Thanks.

**Comment by ASADeveloper** [comment]
Would you please share how you did it?

Thanks.
