### ISSUE TITLE
Integrate Nuba.Finance.Google to Trady.Importer

### ISSUE THREAD

**Issue by lppkarl** [lppkarl/Trady#4]
Refer to: https://github.com/lppkarl/Trady/pull/2

Nuba.Finance.Google: https://github.com/nubasoftware/Nuba.Finance.Google

**Comment by fernaramburu** [comment]
> @lppkarl said _"For the importer, it's architecturally well to divide different importers into different pieces, as a make-all-things-atomic developer, I can't agree more on this. But I wonder if it would be too small for each importer to have its own package. I mean the importer itself only implements a single method, and it's just an adapter to other stock data importing library, e.g. The Trady.Importer.Quandl is referencing Quandl.NET (also 1 of my project). It would have some overhead for users to install some/all of them which may not worth the division. However, we can do this by seperating them into 2 sets, one is Trady.Importer.dll for all bundled, the other is Trady.Importer.xxx.dll for different importers. Is it OK for you for this approach?"_

Fully agree with you! Architecture would be the enemy of being simple :) 
Let's do it as you suggested.

**Comment by lppkarl** [comment]
ok, i would work on the Trady.Importer.dll first & the separated dlls later :)

**Comment by lppkarl** [comment]
The importers have been completed, waiting for merging to "master" when #3 is done
