### ISSUE TITLE
Squeeze Momentum Indicator needed..

### ISSUE THREAD

**Issue by alikalfaoglu** [lppkarl/Trady#40]
Squeeze Momentum Indicator or any sample in c# is also fine. 

I can create a PR and apply it if you don't have time.

Thanks.

**Comment by irperez** [comment]
@alikalfaoglu a PR would be greatly appreciated 👍

**Comment by lppkarl** [comment]
Can't find precise definition of Squeeze Momentum Indicator, only knows it's making use of Bollinger Bands & Keltner Channels, a precise definition is needed to implement the indicator.
