### ISSUE TITLE
How to use candlesticks with backtest?

### ISSUE THREAD

**Issue by ASADeveloper** [lppkarl/Trady#41]
There is already an issue #38 which is closed and probably no one would see it anymore. 
That's why I'm opening a new one hoping some one knows how it is done.

I have a set of candles and I want to determine whether it's a bullish/bearish engulfing pattern or BullishAbandonedBaby using backtest.
I couldn't find any extension that will help me using in buy/sell rules.

Thanks in advance.

**Comment by lppkarl** [comment]
Hi @ASADeveloper Sorry for the late reply. The candlestick pattern recognition is not completed yet, hence the extensions for buy/sell rule, but it would be quite straightforward to create an extension of it using something like 

``` 
public bool IsBullishAbandonedBaby(this IndexedCandle ic)
    => ic.Get<BullishAbandonedBaby>(3, 20, 0.75m, 0.1m)[ic.Index].Tick.IsTrue(t => t);
```

\* The above code is not tested.

**Comment by lppkarl** [comment]
The issue is no longer active, close.
