### ISSUE TITLE
How to get Buy/Sell Signal for last candle?

### ISSUE THREAD

**Issue by mgocean** [lppkarl/Trady#48]
Hello, First of all thanks for the solution.   I am trying to develop bot on this.  The problem is, I cannot get the signal for last (recent) candle.  I tried the following code;

```
IndexedCandle indexedCandle = new IndexedCandle(candles, 1);
if (indexedCandle.IsMacdBullishCross(x, y, z) == true)
{
  Buy....
}

```

Doing something wrong?

**Comment by lppkarl** [comment]
If you're retrieving the signal of the last candle, you should set the second parameter of the indexedcandle to candles.count()-1 instead of 1

**Comment by mgocean** [comment]
Thanks for the fast response I think the following test methods mislead me about the parameter to be set as "1" . But still "candles.count()-1" doesn't catch the "if (indexedCandle.IsMacdBullishCross(x, y, z) == true)" condition.   I will be debugging If I find anything I will share but If you have any root cause analysis result please share.
Thank you.
```
[TestMethod]
        public async Task TestIsBullish()
        {
            var candles = await ImportCandlesAsync();
            var indexedCandle = new IndexedCandle(candles, 1);
            var result = indexedCandle.IsBullish();
            Assert.IsFalse(result);
        }

        [TestMethod]
        public async Task TestIsBearish()
        {
            var candles = await ImportCandlesAsync();
            var indexedCandle = new IndexedCandle(candles, 1);
            var result = indexedCandle.IsBearish();
            Assert.IsTrue(result);
}
```

**Comment by mgocean** [comment]
Hi again,  I found the problematic part 
`public static bool IsTrue(this (AnTick, AnTick, AnTick) obj, Func<AnTick, AnTick, AnTick, bool> predicate)
        {
            Predicate<AnTick> isValid = t => t != null && t.Tick != null && t.Tick.HasValue;
            return isValid(obj.Item1) && isValid(obj.Item2) && isValid(obj.Item3) && predicate(obj.Item1, obj.Item2, obj.Item3);
        }`
always returns false for the following calls
`public static bool IsMacdBullishCross(this IIndexedOhlcv ic, int emaPeriodCount1, int emaPeriodCount2, int demPeriodCount)
            => ic.Get<MovingAverageConvergenceDivergenceHistogram>(emaPeriodCount1, emaPeriodCount2, demPeriodCount).ComputeNeighbour(ic.Index)
                 .IsTrue((prev, current, _) => prev.Tick.IsNegative() && current.Tick.IsPositive());

`

`public static bool IsEmaBullishCross(this IIndexedOhlcv ic, int periodCount1, int periodCount2)
            => ic.Get<ExponentialMovingAverageOscillator>(periodCount1, periodCount2).ComputeNeighbour(ic.Index)
                 .IsTrue((prev, current, _) => prev.Tick.IsNegative() && current.Tick.IsPositive());
`
and for all similar calls isValid(obj.Item3) returns false.

**Comment by lppkarl** [comment]
Related to #53, this issue is closed.
