### ISSUE TITLE
Add setters to IOhlcv 

### ISSUE THREAD

**Issue by pahlot** [lppkarl/Trady#50]
While the current design makes sense to some degree, the fact that there are no setters outside of the constructor limits the ability to serialize/de-serialize instances that inherit from IOhlcv, this especially an issue when passing instances that inherit from IOhlcv via a message bus.

**Comment by lppkarl** [comment]
@pahlot, ya, giving setter to IOhlcv properties actually provide better extensibility on it. It would be good if you could help creating PR for it. Thanks.

**Comment by pahlot** [comment]
@lppkarl done :)

**Comment by lppkarl** [comment]
The beta2 package on this change has been uploaded to nuget. Thanks for the PR
