### ISSUE TITLE
Null Reference Exception

### ISSUE THREAD

**Issue by glide1178** [lppkarl/Trady#52]
Hello, does anyone know why the IsMacdOscBullish rule would throw an exception in this ruleset?

var buyRule = Rule.Create(c => c.IsMacdOscBullish(12, 26, 9))
                                .And(c => c.IsAboveEma(12))
                                .And(c => c.IsAboveEma(26));

However, if I add in a IsFullStoBullishCross condition IsMacdOscBullish does not throw an exception.

var buyRule = Rule.Create(c => c.IsFullStoBullishCross(14, 3, 3))
                                .And(c => c.IsMacdOscBullish(12, 26, 9))
                                .And(c => c.IsAboveEma(12))
                                .And(c => c.IsAboveEma(26));

The exception is being thrown on this line.  Diff returns NULL.

public static bool IsMacdOscBullish(this IIndexedOhlcv ic, int emaPeriodCount1, int emaPeriodCount2, int demPeriodCount)
            => ic.Get<MovingAverageConvergenceDivergenceHistogram>(emaPeriodCount1, emaPeriodCount2, demPeriodCount).Diff(ic.Index).Tick.IsPositive();

  | Name | Value | Type
-- | -- | -- | --
▶ | $exception | {System.NullReferenceException: Object reference not set to an instance of an object.    at Trady.Analysis.Extension.IndexedIOhlcvDataExtension.IsMacdOscBullish(IIndexedOhlcv ic, Int32 emaPeriodCount1, Int32 emaPeriodCount2, Int32 demPeriodCount) in C:\Users\Brian\Documents\TradingApps\Trady-master\Trady.Analysis\Extension\IndexedCandleExtension.cs:line 111    at Trady.Test.BacktestTestMarket.<>c.<BackTestMarket>b__10_0(IIndexedOhlcv c) in C:\Users\Brian\Documents\TradingApps\Trady-master\Trady.Test\BacktestTestMarket.cs:line 108    at Trady.Analysis.Rule.<>c__DisplayClass2_0.<And>b__0(IIndexedOhlcv ic) in C:\Users\Brian\Documents\TradingApps\Trady-master\Trady.Analysis\Rule.cs:line 15    at Trady.Analysis.Rule.<>c__DisplayClass2_0.<And>b__0(IIndexedOhlcv ic) in C:\Users\Brian\Documents\TradingApps\Trady-master\Trady.Analysis\Rule.cs:line 15    at Trady.Analysis.Backtest.Builder.<>c__DisplayClass6_0.<Buy>b__0(IIndexedOhlcv ic) in C:\Users\Brian\Documents\TradingApps\Trady-master\Trady.Analysis\Backtest\Builder.cs:line 34    at Trady.Analysis.Backtest.Runner.<>c__DisplayClass14_0.<CreateBuySellRuleExecutor>b__1(IIndexedOhlcv ic) in C:\Users\Brian\Documents\TradingApps\Trady-master\Trady.Analysis\Backtest\Runner.cs:line 73    at Trady.Analysis.Infrastructure.RuleExecutorBase`3.Execute(Nullable`1 startIndex, Nullable`1 endIndex) in C:\Users\Brian\Documents\TradingApps\Trady-master\Trady.Analysis\Infrastructure\RuleExecutorBase.cs:line 37    at Trady.Analysis.Backtest.Runner.Run(Decimal principal, Decimal premium, Nullable`1 startTime, Nullable`1 endTime) in C:\Users\Brian\Documents\TradingApps\Trady-master\Trady.Analysis\Backtest\Runner.cs:line 60    at Trady.Analysis.Backtest.Runner.<>c__DisplayClass12_0.<RunAsync>b__0() in C:\Users\Brian\Documents\TradingApps\Trady-master\Trady.Analysis\Backtest\Runner.cs:line 36    at System.Threading.Tasks.Task`1.InnerInvoke()    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)} | System.NullReferenceException

**Comment by lppkarl** [comment]
@glide1178 Thanks for the notice, this issue should already be fixed in 9e265d7
