### ISSUE TITLE
Unknown backtesting parameters

### ISSUE THREAD

**Issue by chillydk147** [lppkarl/Trady#55]
Hello, this is a great library, I've just started to look into the backtesting classes and have some questions regarding some parameters which I'm not sure what their purpose is so any help here would be great.

The 2 parameters I'm having difficulty with understanding are "weighting" and "premium". What is their purpose, I've changed the value of 'weighting' but it has no impact of profit value.

```
var imp = new Importer();
var candles = imp.Import("EURUSD", startDate, endDate, PeriodOption.Per15Minute);

// Build buy rule & sell rule based on various patterns
var buyRule = Trady.Analysis.Rule.Create(c => c.IsRsiOversold(14));
var sellRule = Trady.Analysis.Rule.Create(c => c.IsRsiOverbought(14));

// Create portfolio instance by using PortfolioBuilder
//'weighting' value here is 10
Trady.Analysis.Backtest.Runner runner = new Trady.Analysis.Backtest.Builder()
    .Add(candles, 10)
    .Buy(buyRule)
    .Sell(sellRule)
    .Build();

// Start backtesting with the portfolio
//'premium' value here is 1
Trady.Analysis.Backtest.Result result = await runner.RunAsync(10000, 1);
```

**Comment by chillydk147** [comment]
Hi thanks for the response, so the premium value is the cost per transaction, if that's the case then why when I look at the first transaction object does the "AbsoluteCashFlow" property have a value equal to 9999.43560, should if not be 9999. The candle for this buy transaction opened at 1.24840

`var tx = result.Transactions;`

**Comment by glide1178** [comment]
Maybe set some breakpoints in the BuyAsset and SellAsset methods, and you'll get your answer.

**Comment by chillydk147** [comment]
Thanks but how do I do that?, I just have a single line of code which runs the backtest

`Trady.Analysis.Backtest.Result result = runner.Run(10000, 1);`

**Comment by glide1178** [comment]
Download the code.

**Comment by lppkarl** [comment]
Hi @chillydk147 @glide1178 , premium is the cost per transaction, and the weighting is only for use when you want to distribute your money to different stocks. E.g. if you want to distribute $800 to aapl & $200 to fb, you use Builder.Add(candles_for_aapl, 8).Add(candles_for_fb, 2) to do the backtest.

**Comment by lppkarl** [comment]
The parameters for backtest should be explained. Close.
