### ISSUE TITLE
Hull Moving Average Indicator

### ISSUE THREAD

**Issue by maheshlnties** [lppkarl/Trady#58]
Can we get hull moving average indicator?

**Comment by lppkarl** [comment]
@maheshlnties i have to study it first before i can implement the indicator, you may also create a PR on this, it would be a great help 👍

**Comment by maheshlnties** [comment]
I have tried implementing, but i am not getting exact values though. HMA is a derivative calculation from WMA. 
**Calculation:**
1. Calculate a Weighted Moving Average with period n / 2 and multiply it by 2
2. Calculate a Weighted Moving Average for period n and subtract if from step 1
3. Calculate a Weighted Moving Average with period sqrt(n) using the data from step 2
HMA= WMA(2*WMA(n/2) − WMA(n)),sqrt(n))

**Comment by lppkarl** [comment]
@maheshlnties thanks for the formula, i will take a look of it. It seems we need to implement WMA first, and then HMA based on WMA. I will try to implement it this weekend maybe.

**Comment by lppkarl** [comment]
@maheshlnties Both the weighted moving average & hull moving average has been implemented. Please help to check if the calculated value is correct.

**Comment by lppkarl** [comment]
@maheshlnties I find there's some possible reasons for the difference when i was implementing the indicator:

1. If input period is an odd number, what number should be used when using "period / 2" in calculation step 1, should we use the flooring integer or ceiling integer? In my implementation, i have used the flooring one.

2. Same decision happens in step 3, if sqrt(n) is not a whole number, should the sqrt-ed number round-up or round-down? I have used the round-down approach.

I would suspect that the correct one should be some combination of the above 2 cases.

**Comment by maheshlnties** [comment]
@lppkarl Excellent!! Using ceiling integer in step 1 is giving exact values. Thanks a lot once again :)
