### ISSUE TITLE
Demo of integrating to SciChart

### ISSUE THREAD

**Issue by andyb1979** [lppkarl/Trady#61]
Hi Karl, 

I'm interested in making a demo of integrating trading to [SciChart - High Performance WPF Charts](https://www.scichart.com). If I do it, would you put a link in your readme.md?

SciChart is commercial software, not free, but it is very good and allows financial charting in realtime. Also if we see improvements to Trady we're willing to help contribute!

Best regards,
Andrew

**Comment by lppkarl** [comment]
@andyb1979 yea, of course. We can put the link to README.md if you do it, any help is welcomed 👍

**Comment by lppkarl** [comment]
Question being answered. Closed.
