### ISSUE TITLE
Indicator Volume NVI ( negative Volume)

### ISSUE THREAD

**Issue by jotab24** [lppkarl/Trady#71]
Hi! i'm improving to create my own indicator, but i don't know how i can do.

the formula is easy: 

NVI = Previous NVI + {[(Today's Closing Price-Yesterday's Closing Price)/Yesterday's Closing Price)] x Previous NVI}.

can you help me?? Thanks!!!

**Comment by lppkarl** [comment]
Hi @jotab24, You may create a class that inherits from CumulativeNumericAnalyzableBase<IOhlcv, decimal?, AnalyzableTick<decimal?>>. 

In your constructor, call base class with parameters (inputs, c => c.Close) to allow the indicator to use only the close price in the computation step. 

Then, override ComputeInitialValue, you should have the 1st calculated value (NVI) without previous NVI value.

And, also override the ComputeCumulativeValue with your formula:
prevOutputToMap + (mappedInputs[index] - mappedInputs[index - 1])/mappedInputs[index - 1]) * prevOutputToMap

It is a drafted steps for creating a new indicator, i will be updating the document later as I am busy with my work right now. If there's anything you are unable to figure out, please let me know.

**Comment by jotab24** [comment]
ok i have a new class from CumulativeNumericAnalyzableBase, but i need the last NVI value...
the formula is in this website.
Calculation
If today's volume is less than yesterday's volume then:

![image](https://user-images.githubusercontent.com/24636715/46190294-52651d80-c2f3-11e8-9b44-7b3be780637b.png)

If today's volume is greater than or equal to yesterday's volume then:
![image](https://user-images.githubusercontent.com/24636715/46190305-63ae2a00-c2f3-11e8-88bf-8b87e9c0464e.png)

the info is from this website:
 https://www.fidelity.com/learning-center/trading-investing/technical-analysis/technical-indicator-guide/nvi


Can you help me to do it?I wait for the document with desire

thanks a lot

**Comment by lppkarl** [comment]
@jotab24 ok. maybe i will do it this weekend.

**Comment by jotab24** [comment]
thanks a lot!If I understand the manual I will make new indicators!!

**Comment by lppkarl** [comment]
@jotab24 NVI/PVI are added, please help to test the indicator.

**Comment by jotab24** [comment]
Thanks you so much I will test tomorrow!

**Comment by jotab24** [comment]
works as expected!!!Thanks!
