### ISSUE TITLE
multiple SSL-Connections in one project

### ISSUE THREAD

**Issue by SpaceRider79** [lppkarl/Trady#76]
If I first connect to my broker and I second connect to AlphaVantage via Importer and both SSL I get following stackTrace:

HResult = -2146233079
InnerException = {"Die zugrunde liegende Verbindung wurde geschlossen: Für den geschützten SSL/TLS-Kanal konnte keine Vertrauensstellung hergestellt werden.."}
Source = "mscorlib"
StackTrace = "   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59....
Status = TrustFailure

I can't "override" with:

public static class SSLValidator
        {
            private static bool OnValidateCertificate(object sender, X509Certificate certificate, X509Chain chain,
                                                      SslPolicyErrors sslPolicyErrors)
            {
                return true;
            }
            public static void OverrideValidation()
            {
                ServicePointManager.ServerCertificateValidationCallback =
                    OnValidateCertificate;
                ServicePointManager.Expect100Continue = true;
            }
        }

What can I do?

**Comment by lppkarl** [comment]
@SpaceRider79 Would like to know which .net platform you are running the library? Because i think it may be a compatibility issue on the security package with our library. It would probably not what we can resolve if it's the case.

**Comment by SpaceRider79** [comment]
Maybe you can make Client = {System.Net.Http.HttpClient} as public member for manipulations?

I compare both request with fiddler. Only the keep-alive Parameter to broker request is different.

CONNECT www.alphavantage.co:443 HTTP/1.1
Transport
Host: www.alphavantage.co
Connection: Keep-Alive

**Comment by SpaceRider79** [comment]
Today I continued. There is a simple solution. It works for me:

ServicePointManager.CertificatePolicy = null;

It is not your issue . Sorry!

**Comment by lppkarl** [comment]
This issue is resolved.
