### ISSUE TITLE
Add support for crytocurrencies (Bittrex)

### ISSUE THREAD

**Issue by Mike-EEE** [lppkarl/Trady#9]
First off... wow. :)  Thank you for putting this really awesome library together... and in .NET Standard 2.0, even.  I was having to muck around with TA-Lib, which is something straight out of 1985 haha.

I am getting familiar with your importers, but it appears that none of them have access to cryptocurrencies, which is what I am interested in.  Are there plans to make an importer that has access any crypto listings?  If not, I might be interested in helping out here.  FWIW, I use [TradingView](https://www.tradingview.com) which has access to everything.  I am not sure where they get their data, though.  And from surfing their API it doesn't look like they provide the data, just the charts.  I could be wrong, however.

Anyways, wanted to get some thoughts around this and see if I am missing something obvious here. Thanks in advance for any information/assistance!

**Comment by sthewissen** [comment]
Bittrex has a public API endpoint to get their candles e.g:

https://bittrex.com/Api/v2.0/pub/market/GetTicks?marketName=BTC-NEO&tickInterval=fiveMin

Tickinterval has valid values of:

- Hour
- Day
- fiveMin
- oneMin
- thirtyMin

Haven't found one for 15 minutes yet though.

**Comment by Mike-EEE** [comment]
Cooooool... thanks @sthewissen that is good to know.  I didn't even know there was a 2.0 version available as the API that they [discuss on their site](https://bittrex.com/home/api) is 1.1.

I guess the next question I have is what is the typical strategy for importing multiple tickers?  In my case I am wanting to perform calculations on the top 10-20% (maybe more) of coins by volume on Bittrex.  Is it accepted/expected practice to simply cycle through those coins every minute and capture the latest candles for each coin?  Seems pretty intensive.  Would be nice to pass in multiple tickers and get them all in one pass.

One thought I just had was maybe go through and cycle through all coins once for seeding, then call the marketsummaries every minute to update.  I could then use the CSV importer to pull in my data, and simply use what's there now without having to add any new importers.  Hey, I think I just solved my own problem. 😆

**Comment by lppkarl** [comment]
@Mike-EEE the importer is designed to import one ticker for each call as a unit of computation, but i agree that sometimes it's better to return multiple tickers if the provider supports it. It may also benefit importing from csv that contains multiple tickers 😄

**Comment by lppkarl** [comment]
Merged with #21
